name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}  # Doğru parametre ismi 'server'
          username: ${{ secrets.CPANEL_FTP_USER }}  # Doğru parametre ismi 'username'
          password: ${{ secrets.CPANEL_FTP_PASS }}  # Doğru parametre ismi 'password'
          local-dir: "./" 
          server-dir: "/public_html/"  # Doğru parametre ismi 'server-dir'
